---
version: "1.0.0"
slug: stratodns
name: Strato DynDNS
description: >-
  Uses Strato Dynamic DNS service with Let's Encrypt support
url: https://github.com/FabianHardt/strato-dyndns-addon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
hassio_api: true
init: false
image: fabianhardt/{arch}-homeassistant-addon-stratodns
map:
  - ssl:rw
  - share:rw
options:
  domains:
    - null
  aliases: []
  stratoUserName: null
  stratoPassword: null
  lets_encrypt:
    accept_terms: false
    algo: secp384r1
    certfile: fullchain.pem
    keyfile: privkey.pem
  seconds: 300
ports:
  80/tcp: 80
schema:
  domains:
    - str
  aliases:
    - alias: str
      domain: str
  stratoUserName: str
  stratoPassword: password
  lets_encrypt:
    accept_terms: bool
    algo: list(rsa|prime256v1|secp384r1)
    certfile: str
    keyfile: str
  seconds: int
  ipv4: str?
startup: services
